import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class VirtualTryonService {
  private readonly logger = new Logger(VirtualTryonService.name);
  private readonly apiKey: string;

  constructor(private configService: ConfigService) {
    this.apiKey = this.configService.get<string>('GEMINI_API_KEY');
  }

  async generateTryOn(userImageBase64: string, productImageBase64: string): Promise<Buffer> {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${this.apiKey}`;

    const cleanUserImage = userImageBase64.replace(/^data:image\/\w+;base64,/, '');
    const cleanProductImage = productImageBase64.replace(/^data:image\/\w+;base64,/, '');

    const requestBody = {
      contents: [
        {
          parts: [
            { text: "You are a professional virtual try-on AI. Your task is to take the clothing from the 'Product Image' and realistically place it on the person in the 'User Image'. The output should be a single, high-quality, photorealistic image of the person wearing the product. Do not include any text or UI elements. Return the resulting image directly." },
            {
              inlineData: {
                mimeType: "image/jpeg",
                data: cleanUserImage,
              },
            },
            {
              inlineData: {
                mimeType: "image/jpeg",
                data: cleanProductImage,
              },
            },
          ],
        },
      ],
      generationConfig: {
        responseModalities: ["IMAGE", "TEXT"],
      },
    };

    try {
      this.logger.log('Sending request to Gemini 2.0 Flash Exp...');
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        const errorText = await response.text();
        this.logger.error(`Gemini API error: ${response.status} ${errorText}`);
        throw new Error(`Gemini API returned ${response.status}: ${errorText}`);
      }

      const result = await response.json() as any;

      // The response structure for multimodal image generation:
      // candidates[0].content.parts[i].inlineData.data
      const imagePart = result.candidates?.[0]?.content?.parts?.find(
        (part: any) => part.inlineData && part.inlineData.mimeType.startsWith('image/'),
      );

      if (!imagePart) {
        this.logger.error('No image found in Gemini response');
        this.logger.debug(JSON.stringify(result, null, 2));
        throw new Error('No image generated by Gemini. Check the response candidates.');
      }

      this.logger.log('Image generated successfully from Gemini.');
      return Buffer.from(imagePart.inlineData.data, 'base64');
    } catch (error) {
      this.logger.error(`Failed to call Gemini API: ${error.message}`);
      throw error;
    }
  }
}
