import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class VirtualTryonService {
  private readonly logger = new Logger(VirtualTryonService.name);
  private readonly apiKey: string;

  constructor(private configService: ConfigService) {
    this.apiKey = this.configService.get<string>('GEMINI_API_KEY');
  }

  async generateTryOn(userImageBase64: string, productImageBase64: string): Promise<Buffer> {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key=${this.apiKey}`;

    const cleanUserImage = userImageBase64.replace(/^data:image\/\w+;base64,/, '');
    const cleanProductImage = productImageBase64.replace(/^data:image\/\w+;base64,/, '');

    const requestBody = {
      contents: [
        {
          parts: [
            {
              text: "You are a professional virtual try-on AI. Take the clothing from the 'Product Image' and realistically place it on the person in the 'User Image'. Output a single high-quality photorealistic image of the person wearing the product. No text or UI elements.",
            },
            { inlineData: { mimeType: 'image/jpeg', data: cleanUserImage } },
            { inlineData: { mimeType: 'image/jpeg', data: cleanProductImage } },
          ],
        },
      ],
      generationConfig: {
        responseModalities: ['IMAGE', 'TEXT'],
      },
    };

    try {
      this.logger.log('Sending request to Gemini 3.1 Flash Image Preview...');

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        const errorText = await response.text();
        this.logger.error(`Gemini API error: ${response.status} ${errorText}`);
        throw new Error(`Gemini API returned ${response.status}: ${errorText}`);
      }

      const result = await response.json() as any;

      const imagePart = result.candidates?.[0]?.content?.parts?.find(
        (part: any) => part.inlineData && part.inlineData.mimeType.startsWith('image/'),
      );

      if (!imagePart) {
        this.logger.error('No image found in Gemini response');
        this.logger.debug(JSON.stringify(result, null, 2));
        throw new Error('No image generated by Gemini.');
      }

      this.logger.log('Image generated successfully from Gemini.');
      return Buffer.from(imagePart.inlineData.data, 'base64');

    } catch (error) {
      this.logger.error(`Failed to call Gemini API: ${error.message}`);
      throw error;
    }
  }
}